### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by alatteri** [bitfocus/companion-module-barco-dp#1]
@JeffreyDavidsz 

Hi Jeff,

I tried both HDX and DP modules, for the lamp and shutter functions.  I was unable to get either of those operations to work.  Tested nightly 98b14a7-1459 on MacOS.

**Comment by JeffreyDavidsz** [comment]
@alatteri tnx for testing again The module was written with port 43680. You might have a Series 2 projector? I've changed this now, so that you can choose. Also 3 different ways of sending the shutter command. Its in the latest build, when you have the time, could you test it? Tnx

Series 1 projectors
Series 1 projectors are listening on TCP port 0xAAA0 (43680) for incoming connections. The projector IP address can be retrieved by using the Communicator software or Communicator touch panel. Note that the Series 1 DP projectors (DP100, DP90, DP1200, DP1500, DP2000, DP3000), have two IP addresses. One for the main projector controller and one for the Texas Instruments DLP Cinema® front end. The IP address of the projector (main controller) should be used.
To make a connection, you need to create a TCP socket connection with the projector on port 0xAAA0.

Series 2 projectors
Series 2 projectors have a single IP Address. In fact the Texas Instruments DLP Cinema® front end and Barco electronics still have their own IP addresses, but they are behind a router which is embedded into the projector. The internal router is used to forward messages to the appropriate internal board based on the port of the incoming message.
The port number for the Barco protocol is 0xAAD0 (43728).

**Comment by alatteri** [comment]
I was able to access the logs on the projector.  Seems the module is still using port 43680 no matter what the choice is.  
``
8687=Apr 28 18:42:42 DP4K-P local0.info dp61[2147]: main - accepted connection from 192.168.113.31:43680
8692=Apr 28 18:46:14 DP4K-P local0.info dp61[2147]: main - closing connection from 192.168.113.31:43680
8693=Apr 28 18:46:14 DP4K-P local0.info dp61[2147]: main - accepted connection from 192.168.113.31:43680
8694=Apr 28 18:49:36 DP4K-P local0.info dp61[2147]: main - accepted connection from 192.168.113.31:43680
8695=Apr 28 18:49:43 DP4K-P local0.info dp61[2147]: main - closing connection from 192.168.113.31:43680
8700=Apr 28 19:03:17 DP4K-P local0.info dp61[2147]: main - closing connection from 192.168.113.31:43680
8704=Apr 28 19:11:54 DP4K-P local0.info dp61[2147]: main - accepted connection from 192.168.113.31:43680

######Command Sent via Web Interface#####
8707=Apr 28 19:18:34 DP4K-P local0.info dp61[2147]: command (port = 192.168.254.243:43728:35) - set dowser open
8709=Apr 28 19:20:07 DP4K-P local0.info dp61[2147]: command (port = 192.168.254.243:43728:35) - set dowser closed
8712=Apr 28 19:20:57 DP4K-P local0.info dp61[2147]: command (port = 192.168.254.243:43728:35) - execute macro 'Lustre_SDI_B_p3_D63_DCDM_Flat_2K'
8713=Apr 28 19:20:58 DP4K-P local0.info dp61[2147]: command (port = macro) - select light sensor calibration file 'Flat2.2K'
8714=Apr 28 19:20:59 DP4K-P local0.info dp61[2147]: command (port = macro) - execute lens file 'Flat'
8715=Apr 28 19:20:59 DP4K-P local0.info dp61[2147]: system - execute lens file "Flat" handled successfully
8716=Apr 28 19:20:59 DP4K-P local0.info dp61[2147]: command (port = 192.168.254.243:43728:35) - execute macro 'Lustre_SDI_B_rec709_Flat_2K'
8717=Apr 28 19:21:00 DP4K-P local0.info dp61[2147]: command (port = macro) - select light sensor calibration file 'Flat2.2K'
8718=Apr 28 19:21:00 DP4K-P local0.info dp61[2147]: command (port = 192.168.254.243:43728:35) - execute macro 'Lustre_SDI_B_p3_D63_DCDM_Scope_2K'
8719=Apr 28 19:21:01 DP4K-P local0.info dp61[2147]: command (port = macro) - execute lens file 'Flat'
8720=Apr 28 19:21:01 DP4K-P local0.info dp61[2147]: system - execute lens file "Flat" handled successfully
8721=Apr 28 19:21:02 DP4K-P local0.info dp61[2147]: command (port = macro) - select light sensor calibration file 'Scope2.2K'
8722=Apr 28 19:21:03 DP4K-P local0.info dp61[2147]: command (port = macro) - execute lens file 'Scope'
8723=Apr 28 19:21:03 DP4K-P local0.info dp61[2147]: system - execute lens file "Scope" handled successfully
8724=Apr 28 19:21:06 DP4K-P local0.info dp61[2147]: command (port = 192.168.254.243:43728:35) - execute macro 'Lustre_SDI_B_D60_Scope_2K'
8725=Apr 28 19:21:07 DP4K-P local0.info dp61[2147]: command (port = macro) - select light sensor calibration file 'Scope 2k'
8726=Apr 28 19:21:07 DP4K-P local0.info dp61[2147]: command (port = macro) - execute lens file 'Scope'
8727=Apr 28 19:21:08 DP4K-P local0.info dp61[2147]: system - execute lens file "Scope" handled successfully
8728=Apr 28 19:21:09 DP4K-P local0.info dp61[2147]: command (port = 192.168.254.243:43728:35) - execute macro 'AppleTV_Scope'
8729=Apr 28 19:21:10 DP4K-P local0.info dp61[2147]: command (port = macro) - execute lens file 'Scope'
8730=Apr 28 19:21:10 DP4K-P local0.info dp61[2147]: system - execute lens file "Scope" handled successfully
8731=Apr 28 19:21:19 DP4K-P local0.info dp61[2147]: command (port = 192.168.254.243:43728:35) - execute macro 'Lustre_SDI_B_p3_D63_DCDM_Flat_2K'
8732=Apr 28 19:21:20 DP4K-P local0.info dp61[2147]: command (port = macro) - select light sensor calibration file 'Flat2.2K'
8733=Apr 28 19:21:20 DP4K-P local0.info dp61[2147]: command (port = macro) - execute lens file 'Flat'
8734=Apr 28 19:21:20 DP4K-P local0.info dp61[2147]: system - execute lens file "Flat" handled successfully
8736=Apr 28 19:21:51 DP4K-P local0.info dp61[2147]: command (port = 192.168.254.243:43728:35) - set light on
8737=Apr 28 19:22:33 DP4K-P local0.info dp61[2147]: command (port = internal) - set dowser open
8738=Apr 28 19:22:51 DP4K-P local0.info dp61[2147]: command (port = 192.168.254.243:43728:35) - set light off
``

I can telnet to either port and get a response.  Are there some direct commands I could try to run?

`streamdeck@streamdeck01:~ $ telnet 192.168.113.4 43680
Trying 192.168.113.4...
Connected to 192.168.113.4.
Escape character is '^]'.
^]

telnet> quit
Connection closed.
streamdeck@streamdeck01:~ $ telnet 192.168.113.4 43728
Trying 192.168.113.4...
Connected to 192.168.113.4.
Escape character is '^]'.
^]

telnet> quit
Connection closed.`

**Comment by JeffreyDavidsz** [comment]
It looks like the projector accepts both connections, but only works with port 43728. When you change the port and apply can you see connection being made in the projector?

**Comment by alatteri** [comment]
No, with the module I only see connections being made on 43680, even if 43728 is selected.  I should have been more clear in my previous post, the web interface being the Barco Web controller, not Companion web.

**Comment by JeffreyDavidsz** [comment]
To be sure you did press apply right?

**Comment by alatteri** [comment]
Yeah.

**Comment by JeffreyDavidsz** [comment]
creazy stuff

**Comment by JeffreyDavidsz** [comment]
I can force the port number, but try this first; do a telnet connection on 43728 and type
`Turn Lamp Off` or `Turn Lamp On`. These simple commands came from a completely different source

**Comment by alatteri** [comment]
Nothing.

`Enceladus:~ alan$ telnet 192.168.113.4 43728
Trying 192.168.113.4...
Connected to communicator.video.instinctual.studio.
Escape character is '^]'.
Turn Lamp Off

`

**Comment by JeffreyDavidsz** [comment]
Ok I've forced the port number for you, and a little change to the shutter command in the checksum. could you check both options? build number 0f7219b will be ready within 15min

**Comment by alatteri** [comment]
@JeffreyDavidsz   Good news.  Shutter Option 1 Close does work.  None of the others do though. Only Shutter 1 Close.

8425=May  1 01:21:12 DP4K-P local0.info dp61[2147]: command (port = 192.168.113.52:43680:39) - set dowser closed

No other entries in the log when pressing the other functions.

**Comment by JeffreyDavidsz** [comment]
@alatteri did some testing, functions should work now. Would like to add the port option later, just need some confirmation first. Make sure you delete the old actions first.

**Comment by alatteri** [comment]
@JeffreyDavidsz  Amazing... Shutter and Lamp functions now work.  I did not test the lens zoom/focus functions as I don't want to mess up our current configuration.  Can you add macro (preset) selections?  Presets are numbered 1-46, and each one has a name.  See attached photo.
![barco](https://user-images.githubusercontent.com/625982/57032063-45e4d280-6bfe-11e9-973f-a013d844ce79.png)



This is what the logs look like if I select macros in the Barco software.
8601=May  1 17:38:26 DP4K-P local0.info dp61[2147]: command (port = 192.168.113.12:43680:38) - execute macro 'SDI_B_p3_D63_DCDM_Flat_2K'
8605=May  1 17:38:42 DP4K-P local0.info dp61[2147]: command (port = 192.168.113.12:43680:38) - execute macro 'SDI_B_rec709_Flat_2K'
8609=May  1 17:38:46 DP4K-P local0.info dp61[2147]: command (port = 192.168.113.12:43680:38) - execute macro 'SDI_B_rec709_Scope_2K'
8613=May  1 17:38:50 DP4K-P local0.info dp61[2147]: command (port = 192.168.113.12:43680:38) - execute macro 'SDI_B_Flat_2K_422_P3-DCI-Streambox'
8617=May  1 17:38:54 DP4K-P local0.info dp61[2147]: command (port = 192.168.113.12:43680:38) - execute macro 'Flat'

**Comment by JeffreyDavidsz** [comment]
Ok tnx for testing I'll close this one and macro is added please report back I there are any issues
