### ISSUE TITLE
macros

### ISSUE THREAD

**Issue by alatteri** [bitfocus/companion-module-barco-dp#2]
using ff851f4-1482 macros are not working.

I've pasted the macro name directly as is in the Barco software, into Companion.
No entries in Barco log, so maybe the command is not being sent.

**Comment by JeffreyDavidsz** [comment]
It's a bit hard to test without a projector. The command that is sending is `fe 00 e8 81 41 42 43 2f ff` Which is Command `e8 81` like in the manual and `41 42 43` as data (ABC) closed off with the checksum.
Can you telnet yourself? `echo -e '\xfe''\x00''\xe8''\x81''\x41''\x42''\x43''\x2f''\xff' | nc 192.168.0.100 43728` First rename the macro to ABC

**Comment by alatteri** [comment]
@JeffreyDavidsz  I can try in a few hours, projector is back in use.  Maybe we could schedule a TeamViewer session or something so you could try commands directly?

**Comment by alatteri** [comment]
@JeffreyDavidsz  
Seems like it is making a connection, but not executing a command.

[root@localhost ~]# echo -e '\xfe''\x00''\xe8''\x81''\x41''\x42''\x43''\x2f''\xff' | nc 192.168.113.4 43728
??[root@localhost ~]# 


8838=May  1 23:51:25 DP4K-P local0.info dp61[2147]: main - accepted connection from 192.168.113.54:43680
8839=May  1 23:51:25 DP4K-P local0.info dp61[2147]: main - closing connection from 192.168.113.54:4368

**Comment by alatteri** [comment]
@JeffreyDavidsz In reading the documentation, I wonder if this is relevant to the test command.
"Therefore, the length of a C-language string is determined by the position of the NULL character."
and their Hello World example, is closed off with NULL.

'w' | \x77
'o' | \x6f
'r' | \x72
'l' | \x6c
'd' | \x64
NULL | \x00

And the example response from a button, read macro:

Command[1] | \x05
Data[0] | \x02
Data[1] | \x41 (= 'A')
Data[2] | \x42 (= 'B')
Data[3] | \x43 (= 'C')
Data[4] | \x00
Checksum | \xb6

I may totally be wrong, but are we missing a needed NULL to close out the "macro name" string?

**Comment by JeffreyDavidsz** [comment]
Try it! Checksum stays the same

**Comment by alatteri** [comment]
Yup, that was it.

[root@localhost ~]# echo -e '\xfe''\x00''\xe8''\x81''\x41''\x42''\x43''\x00''\x2f''\xff' | nc 192.168.113.4 43728
??[root@localhost ~]# 


9181=May  2 17:57:26 DP4K-P local0.info dp61[2147]: command (port = 192.168.113.54:43680:39) - execute macro 'ABC'

**Comment by JeffreyDavidsz** [comment]
Ok, nice I've added the extra 0x00
